---
- name: Check if Apache is working # name the entire play
  hosts: webservers # will hit all nodes in webserver group. We only have one right now
  vars:
    webserver_message: "I am running to the finish line." # populate variable that will be pulled from jinja2 file
  tasks:
    - name: Start apache2 # just make sure that apache is starter
      service:
        name: apache2
        state: started
    # this block will use the jinja2 source in index.j2 to create a new jinja.html file 
    - name: Create index.html using Jinja2 
      template:
        src: index.j2
        dest: /var/www/html/jinja.html
