---
 - name: Data Manipulation
   hosts: localhost
   gather_facts: false
   vars:
     my_name: Bored Programmer
   tasks:
   - name: Print message
     debug:
       msg:
        - "My name is {{ my_name }}"
        - "My name is {{ my_name | lower }}"
        - "My name is {{ my_name | upper }}"
        - "My name is {{ my_name | capitalize }}"
        - "My name is {{ my_name | title }}"