version: "1.0"
services:
  ansible_manager:
    build: 
      context: '.'
      dockerfile: "./manager/Dockerfile"
    secrets:
      - ssh_keys
    expose: 
      - 22
  ansible_client:
    build: 
      context: '.'
      dockerfile: "./client/Dockerfile"
    secrets:
      - ssh_keys
    expose: 
      - 22
secrets:
  ssh_keys:
    file: ~/.ssh/id_rsa_shared
