# --- indicates a new YAML file, not required but a good idea
---
# Specify Compose file version  specification in place
version: "3.3"
# Define the dictionary of services for compose file
services:
  # Define the dictionary for the ansible_manager service
  # A Service is an abstract definition of a computing resource within an application which can be scaled/replaced independently from other components.
  ansible_manager:
    # Define the build section to define how to create the manager docker image
    build: 
      # Define relative path starting location
      context: '.'
      # Set location of Dockerfile for image build
      dockerfile: "./manager/Dockerfile"
    # define the list of secrets,denoted by - at same level, grants access to sensitive data defined by secrets on a per-service basis.
    secrets:
      - id_rsa
    # define list of exposed ports that Compose implementations MUST expose from container.
    expose: 
      - 22
    networks:
      - ansiblenet
  ansible_client:
  # Define the build section to define how to create the client docker image
    build: 
      # Define relative path starting location
      context: '.'
      # Set location of Dockerfile for image build
      dockerfile: "./client/Dockerfile"
    # Define a volume to gain access to the init script
    volumes: 
      - ./client/init.sh:/init.sh
    # Execute the init script to insert keys
    #  command: sh "mkdir -p /root/.ssh; sh ssh-add -k /run/secrets/id_rsa; service ssh start"
    #command: sh "ssh-add /run/secrets/id_rsa"
    #command: sh init.sh
    # define the list of secrets,denoted by - at same level, grants access to sensitive data defined by secrets on a per-service basis.
    secrets:
      - id_rsa
    # define list of exposed ports that Compose implementations MUST expose from container.
    expose: 
      - 22
    
    networks:
      - ansiblenet
# Secrets section of the compose file to define rsa share form local system
secrets:
  # Define key value pair services can reference
  id_rsa:
    file: ~/.ssh/ansible_id_rsa_shared
networks:
  ansiblenet:
    driver: bridge

